
export interface DocumentConfig {
  logo: {
    url: string;
    noLogo: boolean;
    alignment: 'left' | 'center' | 'right';
    size: number;
  };
  headerOrder: number[];
  tableStyle: string;
  color: string;
  envelopes: boolean;
  company: {
    name: string;
    legalForm: string;
    address: string;
    addressComplement: string;
    zipCode: string;
    city: string;
    country: string;
    phone: string;
    email: string;
    website: string;
    registrationNumber: string;
    rcs: string;
    siret: string;
    naf: string;
    capital: string;
    insurance: string;
    insuranceName: string;
    vatNumber: string;
    vatExempt: boolean;
  };
  label: {
    position: number | string;
    hidden: boolean;
    size: number;
    selected: string;
  };
  header: {
    autoGenerated: boolean;
    customText: string;
  };
  footer: {
    text: string;
  };
  quote: {
    validityPeriod: string;
    number: string;
    notes: string;
    paymentMethods: {
      cheque: boolean;
      cash: boolean;
      bankTransfer: boolean;
      creditCard: boolean;
    };
  };
  invoice: {
    number: string;
    notes: string;
  };
  [key: string]: any;
}
