
import React, { useState } from "react";
import { X, ChevronLeft } from "lucide-react";

// Tab components
import TabMesDocuments from "./documentConfig/TabMesDocuments";
import TabVisuels from "./documentConfig/TabVisuels";
import TabEntreprise from "./documentConfig/TabEntreprise";
import TabLabels from "./documentConfig/TabLabels";
import TabEntetes from "./documentConfig/TabEntetes";
import TabPiedsPages from "./documentConfig/TabPiedsPages";
import TabDevis from "./documentConfig/TabDevis";
import TabFactures from "./documentConfig/TabFactures";

// Types for document configuration
import { DocumentConfig } from "../types/documentConfig";

type DocumentAppearanceConfigProps = {
  onSave: (config: DocumentConfig) => void;
  onCancel: () => void;
  initialConfig?: DocumentConfig;
};

export default function DocumentAppearanceConfig({
  onSave,
  onCancel,
  initialConfig,
}: DocumentAppearanceConfigProps) {
  // Tabs navigation
  const [activeTab, setActiveTab] = useState("visuels");
  
  // Document configuration state
  const [config, setConfig] = useState<DocumentConfig>(
    initialConfig || {
      logo: {
        url: "",
        noLogo: false,
        alignment: "left",
        size: 50,
      },
      headerOrder: [1, 2, 3, 4, 5, 6],
      tableStyle: "style1",
      color: "#8bc34a",
      envelopes: false,
      company: {
        name: "EcoBat SARL",
        legalForm: "SARL",
        address: "votre adresse avec google maps",
        addressComplement: "",
        zipCode: "33400",
        city: "Maville",
        country: "France",
        phone: "01234567890",
        email: "franck+demo@obat.fr",
        website: "http://www.monsiteinternet",
        registrationNumber: "123345465768",
        rcs: "12345767879",
        siret: "12432547687",
        naf: "134R36547658",
        capital: "10",
        insurance: "Biennale",
        insuranceName: "Mon assureur",
        vatNumber: "12335436547657",
        vatExempt: false,
      },
      label: {
        position: 1,
        hidden: false,
        size: 50,
        selected: "rge-eco-artisan",
      },
      header: {
        autoGenerated: true,
        customText: "",
      },
      footer: {
        text: "",
      },
      quote: {
        validityPeriod: "30 jours",
        number: "DEV-201906-00027",
        notes: "",
        paymentMethods: {
          cheque: true,
          cash: true,
          bankTransfer: true,
          creditCard: true,
        },
      },
      invoice: {
        number: "",
        notes: "",
      },
    }
  );

  // Handle changes to the configuration
  const updateConfig = (section: string, data: any) => {
    setConfig({
      ...config,
      [section]: {
        ...config[section as keyof DocumentConfig],
        ...data,
      },
    });
  };

  // Render the appropriate tab content based on activeTab
  const renderTabContent = () => {
    switch (activeTab) {
      case "mes-documents":
        return <TabMesDocuments config={config} updateConfig={updateConfig} />;
      case "visuels":
        return <TabVisuels config={config} updateConfig={updateConfig} />;
      case "entreprise":
        return <TabEntreprise config={config} updateConfig={updateConfig} />;
      case "labels":
        return <TabLabels config={config} updateConfig={updateConfig} />;
      case "entetes":
        return <TabEntetes config={config} updateConfig={updateConfig} />;
      case "pieds-pages":
        return <TabPiedsPages config={config} updateConfig={updateConfig} />;
      case "devis":
        return <TabDevis config={config} updateConfig={updateConfig} />;
      case "factures":
        return <TabFactures config={config} updateConfig={updateConfig} />;
      default:
        return <TabVisuels config={config} updateConfig={updateConfig} />;
    }
  };

  const getTabTitle = () => {
    switch (activeTab) {
      case "mes-documents": return "Mes documents";
      case "visuels": return "Visuels";
      case "entreprise": return "Entreprise";
      case "labels": return "Labels";
      case "entetes": return "Entêtes";
      case "pieds-pages": return "Pieds de pages";
      case "devis": return "Devis";
      case "factures": return "Factures";
      default: return "Visuels";
    }
  };

  return (
    <div className="fixed inset-0 bg-white z-50 flex flex-col">
      {/* Header */}
      <div className="py-3 px-6 border-b border-gray-200 flex justify-between items-center bg-white">
        <h1 className="text-xl font-semibold">Configuration de vos documents</h1>
        <div className="flex gap-2">
          <button
            onClick={onCancel}
            className="px-3 py-1.5 border border-gray-300 rounded text-gray-700 hover:bg-gray-50 text-sm font-medium"
          >
            Annuler
          </button>
          <button
            onClick={() => onSave(config)}
            className="px-3 py-1.5 bg-blue-500 text-white rounded hover:bg-blue-600 text-sm font-medium"
          >
            Enregistrer
          </button>
          <button onClick={onCancel} className="ml-2 text-gray-500 hover:text-gray-700">
            <X className="h-5 w-5" />
          </button>
        </div>
      </div>

      {/* Main content */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left sidebar with tabs */}
        <div className="w-48 border-r border-gray-200 flex flex-col overflow-hidden">
          <div className="p-4 border-b border-gray-200">
            <button 
              className="flex items-center text-gray-500 hover:text-gray-900"
              onClick={() => onCancel()}
            >
              <ChevronLeft className="h-5 w-5" />
              <span className="sr-only">Retour</span>
            </button>
          </div>
          <nav className="flex-1 overflow-y-auto">
            <ul>
              {[
                { id: "mes-documents", label: "Mes documents" },
                { id: "visuels", label: "Visuels" },
                { id: "entreprise", label: "Entreprise" },
                { id: "labels", label: "Labels" },
                { id: "entetes", label: "Entêtes" },
                { id: "pieds-pages", label: "Pieds de pages" },
                { id: "devis", label: "Devis" },
                { id: "factures", label: "Factures" },
              ].map((tab) => (
                <li key={tab.id} className="border-b border-gray-100 last:border-0">
                  <button
                    className={`w-full text-left px-4 py-3 focus:outline-none ${
                      activeTab === tab.id ? "bg-gray-100 font-medium" : "text-gray-700 hover:bg-gray-50"
                    }`}
                    onClick={() => setActiveTab(tab.id)}
                  >
                    {tab.label}
                  </button>
                </li>
              ))}
            </ul>
          </nav>
        </div>

        {/* Main tab content in the middle */}
        <div className="w-1/4 overflow-y-auto p-5 bg-white border-r border-gray-200">
          <h2 className="text-lg font-medium mb-5">{getTabTitle()}</h2>
          {renderTabContent()}
        </div>

        {/* Document preview on the right */}
        <div className="flex-1 bg-gray-50 overflow-y-auto p-4">
          <QuotePreview config={config} />
        </div>
      </div>
    </div>
  );
}

// Preview component for the quote
const QuotePreview = ({ config }: { config: DocumentConfig }) => {
  return (
    <div className="bg-white shadow p-6 max-w-4xl mx-auto">
      {/* Demo quote header */}
      <div className="flex justify-between mb-6">
        <div className="flex items-start">
          {!config.logo.noLogo && (
            <div 
              className={`mr-4 ${
                config.logo.alignment === "left" ? "self-start" : 
                config.logo.alignment === "center" ? "self-center" : 
                "self-end"
              }`}
              style={{ width: `${config.logo.size}px` }}
            >
              {config.logo.url ? (
                <img src={config.logo.url} alt="Logo" className="max-w-full" />
              ) : (
                <div className="bg-gray-200 rounded-full flex items-center justify-center aspect-square">
                  <span className="text-gray-400 text-xs text-center">VOTRE LOGO</span>
                </div>
              )}
            </div>
          )}
          
          <div>
            <h1 className="text-xl font-medium" style={{ color: config.color }}>Devis demo</h1>
            <p className="text-sm">N°{config.quote.number}</p>
            <p className="text-sm">Date de création: 27/06/2019</p>
            <p className="text-sm">Échéance au: 13/06/2019</p>
          </div>
        </div>
        
        <div className="text-right">
          <p className="font-medium">Mme Claire BASTIEN</p>
          <p className="text-sm">236 av. de la République</p>
          <p className="text-sm">49800 TRÉLAZÉ</p>
          <p className="text-sm">France</p>
        </div>
      </div>
      
      {/* Company info */}
      <div className="mb-6">
        <p className="font-medium">{config.company.name}</p>
        <p className="text-sm">{config.company.address}</p>
        <p className="text-sm">{config.company.zipCode} {config.company.city}</p>
        <p className="text-sm">{config.company.country}</p>
        <p className="text-sm">TVA N°{config.company.vatNumber}</p>
        <p className="text-sm">Tél: {config.company.phone}</p>
        <p className="text-sm">Email: {config.company.email}</p>
      </div>
      
      {/* Quote title */}
      <div className="mb-5">
        <h2 className="text-base font-medium">Rénovation restaurant</h2>
      </div>
      
      {/* Quote table */}
      <div className="mb-6 overflow-x-auto">
        <table className={`w-full border-collapse ${
          config.tableStyle === "style1" ? "border border-gray-200" : "border-none"
        }`}>
          <thead>
            <tr style={{ backgroundColor: config.color + "33" }}>
              <th className="py-2 px-2 text-left border-b border-gray-200">N°</th>
              <th className="py-2 px-2 text-left border-b border-gray-200">DESIGNATION</th>
              <th className="py-2 px-2 text-right border-b border-gray-200">QTÉ</th>
              <th className="py-2 px-2 text-right border-b border-gray-200">PRIX U.</th>
              <th className="py-2 px-2 text-right border-b border-gray-200">TVA</th>
              <th className="py-2 px-2 text-right border-b border-gray-200">TOTAL HT</th>
            </tr>
          </thead>
          <tbody>
            <tr className="bg-gray-50">
              <td className="py-2 px-2 border-b border-gray-200">1</td>
              <td className="py-2 px-2 border-b border-gray-200 font-medium">Salle du restaurant</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">3451,63 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.1</td>
              <td className="py-2 px-2 border-b border-gray-200">Coin bar</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">1221,73 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.1.1</td>
              <td className="py-2 px-2 border-b border-gray-200">Peinture du plafond et tâches associées - Préparation, protection, installation échafaudage, dépose des panneaux acoustiques, ponçage, repose des panneaux acoustiques.</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">20,00 m²</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">36,00 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">20,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">720,00 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.1.2</td>
              <td className="py-2 px-2 border-b border-gray-200">Dépose de l'ancienne moquette</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">30,00 m²</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">10,75 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">20,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">322,50 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.1.3</td>
              <td className="py-2 px-2 border-b border-gray-200">
                Cloisons de séparation<br />
                - BA13 standard sur ossature métallique x 1 (m²)<br />
                - Rail R90 et double montant M88 x 1 (m²)<br />
                - Isolation GR80 x 1 (m²)
              </td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">8,75 u</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">11,34 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">20,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">99,23 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.1.4</td>
              <td className="py-2 px-2 border-b border-gray-200">Enlèvement des déchets</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">1,00 u</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">80,00 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">20,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">80,00 €</td>
            </tr>
            <tr className="bg-gray-50">
              <td className="py-2 px-2 border-b border-gray-200">1.2</td>
              <td className="py-2 px-2 border-b border-gray-200 font-medium">Salle à l'étage</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right"></td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">2229,90 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.2.1</td>
              <td className="py-2 px-2 border-b border-gray-200">Pose d'un nouveau revêtement de sol spécial restaurant</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">30,00 m²</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">62,00 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">10,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">1860,00 €</td>
            </tr>
            <tr>
              <td className="py-2 px-2 border-b border-gray-200">1.2.2</td>
              <td className="py-2 px-2 border-b border-gray-200">Application d'un ragréage</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">30,00 m²</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">12,33 €</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">10,00%</td>
              <td className="py-2 px-2 border-b border-gray-200 text-right">369,90 €</td>
            </tr>
          </tbody>
        </table>
      </div>
      
      {/* Payment info */}
      <div className="flex justify-between">
        <div>
          <h3 className="text-sm font-medium mb-2">Conditions de paiement</h3>
          <p className="text-sm">
            Méthodes de paiement acceptées : 
            {config.quote.paymentMethods.cheque && " Chèque,"}
            {config.quote.paymentMethods.cash && " Espèces,"}
            {config.quote.paymentMethods.bankTransfer && " Virement bancaire"}
            {config.quote.paymentMethods.creditCard && (config.quote.paymentMethods.bankTransfer ? "." : ", Carte bancaire.")}
          </p>
        </div>
        
        <div className="text-right">
          <div className="flex justify-between mb-1">
            <span className="mr-8">Total net HT</span>
            <span>2767,23 €</span>
          </div>
          <div className="flex justify-between mb-1">
            <span className="mr-8">TVA 10,00 %</span>
            <span>222,99 €</span>
          </div>
          <div className="flex justify-between mb-4">
            <span className="mr-8">TVA 20,00 %</span>
            <span>107,55 €</span>
          </div>
          <div className="flex justify-between font-medium px-4 py-2" style={{ backgroundColor: config.color + "66" }}>
            <span className="mr-8">TOTAL NET TTC</span>
            <span>3098,17 €</span>
          </div>
        </div>
      </div>
    </div>
  );
};

