
import { useState, useEffect } from "react";
import { Navbar } from "./Navbar";
import { Outlet } from "react-router-dom";
import { Eye, Pencil } from "lucide-react";
import AppearanceConfigButton from "./AppearanceConfigButton";

export function Layout() {
  const [showSidebar, setShowSidebar] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [mode, setMode] = useState<"edit" | "preview">("edit");

  // Check for mobile view
  useEffect(() => {
    const checkIfMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    
    checkIfMobile();
    window.addEventListener('resize', checkIfMobile);
    
    return () => {
      window.removeEventListener('resize', checkIfMobile);
    };
  }, []);

  return (
    <div className="flex h-screen bg-white">
      {/* Sidebar toggle area - narrow strip on the left edge */}
      {!isMobile && (
        <div 
          className="fixed top-0 left-0 h-screen w-2 z-40 hover:cursor-pointer bg-transparent"
          onMouseEnter={() => setShowSidebar(true)}
        />
      )}
      
      {/* Navbar that shows on hover */}
      <div 
        className={`fixed top-0 left-0 h-screen transition-all duration-300 z-30 ${
          showSidebar ? "translate-x-0" : "-translate-x-full"
        } ${isMobile ? "hidden" : "block"}`}
        onMouseLeave={() => setShowSidebar(false)}
      >
        <Navbar />
      </div>
      
      {/* Show mobile navbar on small screens */}
      {isMobile && (
        <div className="block z-30">
          <Navbar />
        </div>
      )}
      
      {/* Main content takes full width */}
      <div className="flex-1 min-h-screen flex flex-col w-full">
        {/* Top bar for mode switching in quote view */}
        <div className="bg-gray-800 text-white py-2 px-3 flex justify-between items-center">
          <div className="flex space-x-2">
            <button 
              onClick={() => setMode("edit")} 
              className={`flex items-center px-3 py-1 rounded text-sm ${
                mode === "edit" ? "bg-gray-700" : "hover:bg-gray-700"
              }`}
            >
              <Pencil className="h-4 w-4 mr-1.5" />
              Édition
            </button>
            <button 
              onClick={() => setMode("preview")} 
              className={`flex items-center px-3 py-1 rounded text-sm ${
                mode === "preview" ? "bg-gray-700" : "hover:bg-gray-700"
              }`}
            >
              <Eye className="h-4 w-4 mr-1.5" />
              Prévisualisation
            </button>
          </div>
          
          {mode === "preview" && (
            <div className="flex items-center space-x-2">
              <AppearanceConfigButton 
                initialConfig={{
                  logo: {
                    url: "",
                    noLogo: false,
                    alignment: "left",
                    size: 50,
                  },
                  headerOrder: [1, 2, 3, 4, 5, 6],
                  tableStyle: "style1",
                  color: "#8bc34a",
                  envelopes: false,
                  company: {
                    name: "EcoBat SARL",
                    legalForm: "SARL",
                    address: "votre adresse avec google maps",
                    addressComplement: "",
                    zipCode: "33400",
                    city: "Maville",
                    country: "France",
                    phone: "01234567890",
                    email: "franck+demo@obat.fr",
                    website: "http://www.monsiteinternet",
                    registrationNumber: "123345465768",
                    rcs: "12345767879",
                    siret: "12432547687",
                    naf: "134R36547658",
                    capital: "10",
                    insurance: "Biennale",
                    insuranceName: "Mon assureur",
                    vatNumber: "12335436547657",
                    vatExempt: false,
                  },
                  label: {
                    position: 1,
                    hidden: false,
                    size: 50,
                    selected: "rge-eco-artisan",
                  },
                  header: {
                    autoGenerated: true,
                    customText: "",
                  },
                  footer: {
                    text: "",
                  },
                  quote: {
                    validityPeriod: "30 jours",
                    number: "DEV-201906-00027",
                    notes: "",
                    paymentMethods: {
                      cheque: true,
                      cash: true,
                      bankTransfer: true,
                      creditCard: true,
                    },
                  },
                  invoice: {
                    number: "",
                    notes: "",
                  },
                }}
                onSave={(config) => {
                  console.log("Configuration saved:", config);
                }}
              />
              <button className="px-3 py-1 bg-red-600 text-white rounded hover:bg-red-700 text-sm">
                Annuler
              </button>
              <button className="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700 text-sm">
                Enregistrer
              </button>
              <div className="px-3 py-1 bg-green-600 text-white rounded hover:bg-green-700 cursor-pointer text-sm">
                Finaliser et envoyer
              </div>
            </div>
          )}
        </div>
        
        <Outlet />
      </div>
    </div>
  );
}
