
import React from "react";
import { DocumentConfig } from "../../types/documentConfig";

type TabEntetesProps = {
  config: DocumentConfig;
  updateConfig: (section: string, data: any) => void;
};

const TabEntetes = ({ config, updateConfig }: TabEntetesProps) => {
  const handleHeaderChange = (data: Partial<DocumentConfig["header"]>) => {
    updateConfig("header", data);
  };

  const generateAutoText = () => {
    return `${config.company.name}
${config.company.address}
${config.company.zipCode} ${config.company.city}
${config.company.country}
TVA N°${config.company.vatNumber}
Tél : ${config.company.phone}
Email : ${config.company.email}`;
  };

  return (
    <div className="space-y-6">
      <div>
        <div className="mb-4">
          <div className="flex items-center mb-3">
            <input 
              type="radio" 
              id="auto-text" 
              name="header-type"
              checked={config.header.autoGenerated} 
              onChange={() => handleHeaderChange({ autoGenerated: true })}
              className="mr-2" 
            />
            <label htmlFor="auto-text" className="text-sm font-medium">Texte généré automatiquement</label>
          </div>
          <div className="flex items-center">
            <input 
              type="radio" 
              id="custom-text" 
              name="header-type"
              checked={!config.header.autoGenerated} 
              onChange={() => handleHeaderChange({ autoGenerated: false })}
              className="mr-2" 
            />
            <label htmlFor="custom-text" className="text-sm font-medium">Texte libre</label>
          </div>
        </div>

        <textarea 
          value={config.header.autoGenerated ? generateAutoText() : config.header.customText}
          onChange={(e) => handleHeaderChange({ customText: e.target.value })}
          disabled={config.header.autoGenerated}
          className="w-full px-3 py-2 border border-gray-300 rounded-md h-40 bg-gray-50"
        />
      </div>
    </div>
  );
};

export default TabEntetes;
